#!/bin/bash

echo "============================================"
echo "GitHub Repository Setup for NYC Rare Birds"
echo "============================================"
echo ""
echo "GitHub Username: AreebaFatimaa"
echo "Repository Name: nyc-rare-birds"
echo ""
echo "STEP 1: Create the GitHub repository"
echo "----------------------------------------"
echo "Please open this URL in your browser:"
echo "https://github.com/new?name=nyc-rare-birds&description=Interactive+map+of+rare+bird+sightings+in+NYC&visibility=public"
echo ""
echo "This will pre-fill the form with:"
echo "  - Repository name: nyc-rare-birds"
echo "  - Description: Interactive map of rare bird sightings in NYC"
echo "  - Visibility: Public (required for free GitHub Pages)"
echo ""
echo "IMPORTANT: Do NOT check 'Add a README file' or any other options"
echo "Just click 'Create repository'"
echo ""
read -p "Press ENTER after you've created the repository on GitHub..."
echo ""

echo "STEP 2: Pushing code to GitHub"
echo "----------------------------------------"
git remote add origin https://github.com/AreebaFatimaa/nyc-rare-birds.git
git branch -M main

echo "Pushing to GitHub..."
git push -u origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ SUCCESS! Code pushed to GitHub"
    echo ""
    echo "STEP 3: Configure GitHub Secrets and Pages"
    echo "----------------------------------------"
    echo ""
    echo "1. Get your eBird API key from: https://ebird.org/api/keygen"
    echo ""
    echo "2. Add API key to GitHub Secrets:"
    echo "   https://github.com/AreebaFatimaa/nyc-rare-birds/settings/secrets/actions/new"
    echo "   - Name: EBIRD_API_KEY"
    echo "   - Secret: [paste your eBird API key]"
    echo "   - Click 'Add secret'"
    echo ""
    echo "3. Enable GitHub Pages:"
    echo "   https://github.com/AreebaFatimaa/nyc-rare-birds/settings/pages"
    echo "   - Source: Deploy from a branch"
    echo "   - Branch: main"
    echo "   - Folder: / (root)"
    echo "   - Click 'Save'"
    echo ""
    echo "4. Run the first workflow:"
    echo "   https://github.com/AreebaFatimaa/nyc-rare-birds/actions/workflows/update-birds.yml"
    echo "   - Click 'Run workflow' button"
    echo "   - Click 'Run workflow' again to confirm"
    echo ""
    echo "Your site will be live at:"
    echo "https://areebafatimaa.github.io/nyc-rare-birds"
    echo ""
else
    echo ""
    echo "❌ Error pushing to GitHub"
    echo "This might be because:"
    echo "  1. Repository doesn't exist yet - create it first"
    echo "  2. Authentication failed - you may need to set up credentials"
    echo ""
fi
